name: Build Release Artifacts

on:
  release:
    types: [created]

jobs:
  release-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: ./build_linux.sh

  release-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: ./build.bat

  release-upload:
    runs-on: ubuntu-20.04
    needs: [release-linux, release-windows]
    steps:
      - name: Upload artifacts
        uses: Roang-zero1/github-upload-release-artifacts-action@v2
        with:
          args: "atmosim atmosim.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
